import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  characterCreationSidebar: [
    {
      type: 'category',
      label: 'Basics',
      items: [{ type: 'autogenerated', dirName: 'character/basics' }],
    },
    {
      type: 'category',
      label: 'Foundation',
      items: [{ type: 'autogenerated', dirName: 'character/foundation' }],
    },
    {
      type: 'category',
      label: 'Classes',
      items: [{ type: 'autogenerated', dirName: 'character/classes' }],
    },
    {
      type: 'category',
      label: 'Skills',
      items: [{ type: 'autogenerated', dirName: 'character/skills' }],
    },
    {
      type: 'category',
      label: 'Equipment',
      items: [{ type: 'autogenerated', dirName: 'character/equipment' }],
    },
    {
      type: 'doc',
      id: 'character/index', // Refers to docs/character/index.md
      label: 'Overview',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
